services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_DB=settlement'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'